### ISSUE TITLE
Wave 2 - Weapon Improvement and Balancing

### ISSUE THREAD

**Issue by LEGOAnimal22** [LEGOAnimal22/Project_Hero_C#6]
## **Tasks**
* [ ] Create new classifications for weapons
* [ ] Fix whatever broke after doing that...
* [ ] Alter the Weapon Action function to accommodate for the new power scale
* [ ] Test and balance weapons

## **Progress**
* Added new classifications for weapons: category, handling, weight, range, and damage type
* Change weapon power from a short to a char

## **Ideas** 
* Add a duel-wield mechanic for one-handed weapons?
