### ISSUE TITLE
Wave 2 - Stat Balancing

### ISSUE THREAD

**Issue by LEGOAnimal22** [LEGOAnimal22/Project_Hero_C#7]
## **Tasks**
* [ ] Reduce overall stats
* [ ] Reduce rank bonuses
* [ ] Update current tests
* [ ] Test and adjust

## **Progress**
* You now start off with 60 Attack / Speed and 100 Health, to make the game a little more difficult
* Rank bonuses were reduced by at least 70%
